In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import tensorflow as tf

In [3]:
#Reading dataset
dataset=pd.read_csv("D:/Machine Learning/Datasets/MinorProjectDataset/archive (5)/dataset.csv",skipinitialspace = True)

In [4]:
print(dataset)

                                      Disease            Symptom_1  \
0                            Fungal infection              itching   
1                            Fungal infection            skin_rash   
2                            Fungal infection              itching   
3                            Fungal infection              itching   
4                            Fungal infection              itching   
...                                       ...                  ...   
4915  (vertigo) Paroymsal  Positional Vertigo             vomiting   
4916                                     Acne            skin_rash   
4917                  Urinary tract infection  burning_micturition   
4918                                Psoriasis            skin_rash   
4919                                 Impetigo            skin_rash   

                 Symptom_2             Symptom_3                 Symptom_4  \
0                skin_rash  nodal_skin_eruptions       dischromic _patches   
1  

In [5]:
#Converting dataset into a pandas dataframe
dataframe=pd.DataFrame(dataset)

In [6]:
dataframe

Disease            Symptom_1  \
0                            Fungal infection              itching   
1                            Fungal infection            skin_rash   
2                            Fungal infection              itching   
3                            Fungal infection              itching   
4                            Fungal infection              itching   
...                                       ...                  ...   
4915  (vertigo) Paroymsal  Positional Vertigo             vomiting   
4916                                     Acne            skin_rash   
4917                  Urinary tract infection  burning_micturition   
4918                                Psoriasis            skin_rash   
4919                                 Impetigo            skin_rash   

                 Symptom_2             Symptom_3                 Symptom_4  \
0                skin_rash  nodal_skin_eruptions       dischromic _patches   
1     nodal_skin_eruptions   dischromic _patches                       NaN   
2     nodal_skin_eruptions   dischromic _patches                       NaN   
3                skin_rash   dischromic _patches                       NaN   
4                skin_rash  nodal_skin_eruptions                       NaN   
...                    ...                   ...                       ...   
4915              headache                nausea        spinning_movements   
4916    pus_filled_pimples            blackheads                  scurring   
4917    bladder_discomfort   foul_smell_of urine  continuous_feel_of_urine   
4918            joint_pain          skin_peeling       silver_like_dusting   
4919            high_fever               blister      red_sore_around_nose   

                 Symptom_5           Symptom_6 Symptom_7 Symptom_8 Symptom_9  \
0                      NaN                 NaN       NaN       NaN       NaN   
1                      NaN                 NaN       NaN       NaN       NaN   
2                      NaN                 NaN       NaN       NaN       NaN   
3                      NaN                 NaN       NaN       NaN       NaN   
4                      NaN                 NaN       NaN       NaN       NaN   
...                    ...                 ...       ...       ...       ...   
4915       loss_of_balance        unsteadiness       NaN       NaN       NaN   
4916                   NaN                 NaN       NaN       NaN       NaN   
4917                   NaN                 NaN       NaN       NaN       NaN   
4918  small_dents_in_nails  inflammatory_nails       NaN       NaN       NaN   
4919     yellow_crust_ooze                 NaN       NaN       NaN       NaN   

     Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14 Symptom_15  \
0           NaN        NaN        NaN        NaN        NaN        NaN   
1           NaN        NaN        NaN        NaN        NaN        NaN   
2           NaN        NaN        NaN        NaN        NaN        NaN   
3           NaN        NaN        NaN        NaN        NaN        NaN   
4           NaN        NaN        NaN        NaN        NaN        NaN   
...         ...        ...        ...        ...        ...        ...   
4915        NaN        NaN        NaN        NaN        NaN        NaN   
4916        NaN        NaN        NaN        NaN        NaN        NaN   
4917        NaN        NaN        NaN        NaN        NaN        NaN   
4918        NaN        NaN        NaN        NaN        NaN        NaN   
4919        NaN        NaN        NaN        NaN        NaN        NaN   

     Symptom_16 Symptom_17  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
4915        NaN        NaN  
4916        NaN        NaN  
4917        NaN        NaN  
4918        NaN        NaN  
4919        NaN        NaN  

[4920 rows x 18 columns]

In [7]:
#Substituting Null values with 0
dataframe=dataframe.fillna(0)

In [8]:
dataframe.describe()

Disease Symptom_1 Symptom_2 Symptom_3   Symptom_4  Symptom_5  \
count               4920      4920      4920      4920        4920       4920   
unique                41        34        48        54          51         39   
top     Fungal infection  vomiting  vomiting   fatigue  high_fever          0   
freq                 120       822       870       726         378       1206   

        Symptom_6  Symptom_7  Symptom_8  Symptom_9  Symptom_10  Symptom_11  \
count        4920       4920       4920       4920        4920        4920   
unique         33         27         22         23          22          19   
top             0          0          0          0           0           0   
freq         1986       2652       2976       3228        3408        3726   

        Symptom_12  Symptom_13  Symptom_14  Symptom_15  Symptom_16  Symptom_17  
count         4920        4920        4920        4920        4920        4920  
unique          12           9           5           4           4           2  
top              0           0           0           0           0           0  
freq          4176        4416        4614        4680        4728        4848

In [9]:
df1=pd.read_csv('D:/Machine Learning/Datasets/MinorProjectDataset/archive (5)/Symptom-severity.csv')
df1=pd.DataFrame(df1)

In [10]:
dataframe

Disease            Symptom_1  \
0                            Fungal infection              itching   
1                            Fungal infection            skin_rash   
2                            Fungal infection              itching   
3                            Fungal infection              itching   
4                            Fungal infection              itching   
...                                       ...                  ...   
4915  (vertigo) Paroymsal  Positional Vertigo             vomiting   
4916                                     Acne            skin_rash   
4917                  Urinary tract infection  burning_micturition   
4918                                Psoriasis            skin_rash   
4919                                 Impetigo            skin_rash   

                 Symptom_2             Symptom_3                 Symptom_4  \
0                skin_rash  nodal_skin_eruptions       dischromic _patches   
1     nodal_skin_eruptions   dischromic _patches                         0   
2     nodal_skin_eruptions   dischromic _patches                         0   
3                skin_rash   dischromic _patches                         0   
4                skin_rash  nodal_skin_eruptions                         0   
...                    ...                   ...                       ...   
4915              headache                nausea        spinning_movements   
4916    pus_filled_pimples            blackheads                  scurring   
4917    bladder_discomfort   foul_smell_of urine  continuous_feel_of_urine   
4918            joint_pain          skin_peeling       silver_like_dusting   
4919            high_fever               blister      red_sore_around_nose   

                 Symptom_5           Symptom_6 Symptom_7 Symptom_8 Symptom_9  \
0                        0                   0         0         0         0   
1                        0                   0         0         0         0   
2                        0                   0         0         0         0   
3                        0                   0         0         0         0   
4                        0                   0         0         0         0   
...                    ...                 ...       ...       ...       ...   
4915       loss_of_balance        unsteadiness         0         0         0   
4916                     0                   0         0         0         0   
4917                     0                   0         0         0         0   
4918  small_dents_in_nails  inflammatory_nails         0         0         0   
4919     yellow_crust_ooze                   0         0         0         0   

     Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14 Symptom_15  \
0             0          0          0          0          0          0   
1             0          0          0          0          0          0   
2             0          0          0          0          0          0   
3             0          0          0          0          0          0   
4             0          0          0          0          0          0   
...         ...        ...        ...        ...        ...        ...   
4915          0          0          0          0          0          0   
4916          0          0          0          0          0          0   
4917          0          0          0          0          0          0   
4918          0          0          0          0          0          0   
4919          0          0          0          0          0          0   

     Symptom_16 Symptom_17  
0             0          0  
1             0          0  
2             0          0  
3             0          0  
4             0          0  
...         ...        ...  
4915          0          0  
4916          0          0  
4917          0          0  
4918          0          0  
4919          0          0  

[4920 rows x 18 columns]

In [11]:
df1

Symptom  weight
0                 itching       1
1               skin_rash       3
2    nodal_skin_eruptions       4
3     continuous_sneezing       4
4               shivering       5
..                    ...     ...
128    inflammatory_nails       2
129               blister       4
130  red_sore_around_nose       2
131     yellow_crust_ooze       3
132             prognosis       5

[133 rows x 2 columns]

In [12]:
dataframe

Disease            Symptom_1  \
0                            Fungal infection              itching   
1                            Fungal infection            skin_rash   
2                            Fungal infection              itching   
3                            Fungal infection              itching   
4                            Fungal infection              itching   
...                                       ...                  ...   
4915  (vertigo) Paroymsal  Positional Vertigo             vomiting   
4916                                     Acne            skin_rash   
4917                  Urinary tract infection  burning_micturition   
4918                                Psoriasis            skin_rash   
4919                                 Impetigo            skin_rash   

                 Symptom_2             Symptom_3                 Symptom_4  \
0                skin_rash  nodal_skin_eruptions       dischromic _patches   
1     nodal_skin_eruptions   dischromic _patches                         0   
2     nodal_skin_eruptions   dischromic _patches                         0   
3                skin_rash   dischromic _patches                         0   
4                skin_rash  nodal_skin_eruptions                         0   
...                    ...                   ...                       ...   
4915              headache                nausea        spinning_movements   
4916    pus_filled_pimples            blackheads                  scurring   
4917    bladder_discomfort   foul_smell_of urine  continuous_feel_of_urine   
4918            joint_pain          skin_peeling       silver_like_dusting   
4919            high_fever               blister      red_sore_around_nose   

                 Symptom_5           Symptom_6 Symptom_7 Symptom_8 Symptom_9  \
0                        0                   0         0         0         0   
1                        0                   0         0         0         0   
2                        0                   0         0         0         0   
3                        0                   0         0         0         0   
4                        0                   0         0         0         0   
...                    ...                 ...       ...       ...       ...   
4915       loss_of_balance        unsteadiness         0         0         0   
4916                     0                   0         0         0         0   
4917                     0                   0         0         0         0   
4918  small_dents_in_nails  inflammatory_nails         0         0         0   
4919     yellow_crust_ooze                   0         0         0         0   

     Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14 Symptom_15  \
0             0          0          0          0          0          0   
1             0          0          0          0          0          0   
2             0          0          0          0          0          0   
3             0          0          0          0          0          0   
4             0          0          0          0          0          0   
...         ...        ...        ...        ...        ...        ...   
4915          0          0          0          0          0          0   
4916          0          0          0          0          0          0   
4917          0          0          0          0          0          0   
4918          0          0          0          0          0          0   
4919          0          0          0          0          0          0   

     Symptom_16 Symptom_17  
0             0          0  
1             0          0  
2             0          0  
3             0          0  
4             0          0  
...         ...        ...  
4915          0          0  
4916          0          0  
4917          0          0  
4918          0          0  
4919          0          0  

[4920 rows x 18 columns]

In [13]:
symptom_values=df1['Symptom'].unique()
symptom_values

array(['itching', 'skin_rash', 'nodal_skin_eruptions',
       'continuous_sneezing', 'shivering', 'chills', 'joint_pain',
       'stomach_pain', 'acidity', 'ulcers_on_tongue', 'muscle_wasting',
       'vomiting', 'burning_micturition', 'spotting_urination', 'fatigue',
       'weight_gain', 'anxiety', 'cold_hands_and_feets', 'mood_swings',
       'weight_loss', 'restlessness', 'lethargy', 'patches_in_throat',
       'irregular_sugar_level', 'cough', 'high_fever', 'sunken_eyes',
       'breathlessness', 'sweating', 'dehydration', 'indigestion',
       'headache', 'yellowish_skin', 'dark_urine', 'nausea',
       'loss_of_appetite', 'pain_behind_the_eyes', 'back_pain',
       'constipation', 'abdominal_pain', 'diarrhoea', 'mild_fever',
       'yellow_urine', 'yellowing_of_eyes', 'acute_liver_failure',
       'fluid_overload', 'swelling_of_stomach', 'swelled_lymph_nodes',
       'malaise', 'blurred_and_distorted_vision', 'phlegm',
       'throat_irritation', 'redness_of_eyes', 'sinus_pressu

In [14]:
disease_values=dataframe['Disease'].unique()

In [15]:
disease_values

array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object)

In [16]:
disease_values_list=disease_values.tolist()
disease_values_list

['Fungal infection',
 'Allergy',
 'GERD',
 'Chronic cholestasis',
 'Drug Reaction',
 'Peptic ulcer diseae',
 'AIDS',
 'Diabetes ',
 'Gastroenteritis',
 'Bronchial Asthma',
 'Hypertension ',
 'Migraine',
 'Cervical spondylosis',
 'Paralysis (brain hemorrhage)',
 'Jaundice',
 'Malaria',
 'Chicken pox',
 'Dengue',
 'Typhoid',
 'hepatitis A',
 'Hepatitis B',
 'Hepatitis C',
 'Hepatitis D',
 'Hepatitis E',
 'Alcoholic hepatitis',
 'Tuberculosis',
 'Common Cold',
 'Pneumonia',
 'Dimorphic hemmorhoids(piles)',
 'Heart attack',
 'Varicose veins',
 'Hypothyroidism',
 'Hyperthyroidism',
 'Hypoglycemia',
 'Osteoarthristis',
 'Arthritis',
 '(vertigo) Paroymsal  Positional Vertigo',
 'Acne',
 'Urinary tract infection',
 'Psoriasis',
 'Impetigo']

In [17]:
#Encoding Disease Values in dataframe :
for i in dataframe.index:
  dataframe['Disease'][i]=disease_values_list.index(dataframe['Disease'][i])+1

In [18]:
dataframe

Disease            Symptom_1             Symptom_2             Symptom_3  \
0          1              itching             skin_rash  nodal_skin_eruptions   
1          1            skin_rash  nodal_skin_eruptions   dischromic _patches   
2          1              itching  nodal_skin_eruptions   dischromic _patches   
3          1              itching             skin_rash   dischromic _patches   
4          1              itching             skin_rash  nodal_skin_eruptions   
...      ...                  ...                   ...                   ...   
4915      37             vomiting              headache                nausea   
4916      38            skin_rash    pus_filled_pimples            blackheads   
4917      39  burning_micturition    bladder_discomfort   foul_smell_of urine   
4918      40            skin_rash            joint_pain          skin_peeling   
4919      41            skin_rash            high_fever               blister   

                     Symptom_4             Symptom_5           Symptom_6  \
0          dischromic _patches                     0                   0   
1                            0                     0                   0   
2                            0                     0                   0   
3                            0                     0                   0   
4                            0                     0                   0   
...                        ...                   ...                 ...   
4915        spinning_movements       loss_of_balance        unsteadiness   
4916                  scurring                     0                   0   
4917  continuous_feel_of_urine                     0                   0   
4918       silver_like_dusting  small_dents_in_nails  inflammatory_nails   
4919      red_sore_around_nose     yellow_crust_ooze                   0   

     Symptom_7 Symptom_8 Symptom_9 Symptom_10 Symptom_11 Symptom_12  \
0            0         0         0          0          0          0   
1            0         0         0          0          0          0   
2            0         0         0          0          0          0   
3            0         0         0          0          0          0   
4            0         0         0          0          0          0   
...        ...       ...       ...        ...        ...        ...   
4915         0         0         0          0          0          0   
4916         0         0         0          0          0          0   
4917         0         0         0          0          0          0   
4918         0         0         0          0          0          0   
4919         0         0         0          0          0          0   

     Symptom_13 Symptom_14 Symptom_15 Symptom_16 Symptom_17  
0             0          0          0          0          0  
1             0          0          0          0          0  
2             0          0          0          0          0  
3             0          0          0          0          0  
4             0          0          0          0          0  
...         ...        ...        ...        ...        ...  
4915          0          0          0          0          0  
4916          0          0          0          0          0  
4917          0          0          0          0          0  
4918          0          0          0          0          0  
4919          0          0          0          0          0  

[4920 rows x 18 columns]

In [19]:
symptom_values_list=symptom_values.tolist()
symptom_values_list

['itching',
 'skin_rash',
 'nodal_skin_eruptions',
 'continuous_sneezing',
 'shivering',
 'chills',
 'joint_pain',
 'stomach_pain',
 'acidity',
 'ulcers_on_tongue',
 'muscle_wasting',
 'vomiting',
 'burning_micturition',
 'spotting_urination',
 'fatigue',
 'weight_gain',
 'anxiety',
 'cold_hands_and_feets',
 'mood_swings',
 'weight_loss',
 'restlessness',
 'lethargy',
 'patches_in_throat',
 'irregular_sugar_level',
 'cough',
 'high_fever',
 'sunken_eyes',
 'breathlessness',
 'sweating',
 'dehydration',
 'indigestion',
 'headache',
 'yellowish_skin',
 'dark_urine',
 'nausea',
 'loss_of_appetite',
 'pain_behind_the_eyes',
 'back_pain',
 'constipation',
 'abdominal_pain',
 'diarrhoea',
 'mild_fever',
 'yellow_urine',
 'yellowing_of_eyes',
 'acute_liver_failure',
 'fluid_overload',
 'swelling_of_stomach',
 'swelled_lymph_nodes',
 'malaise',
 'blurred_and_distorted_vision',
 'phlegm',
 'throat_irritation',
 'redness_of_eyes',
 'sinus_pressure',
 'runny_nose',
 'congestion',
 'chest_pain',
 

In [20]:
#Encoding the symptom values in the data frame
categories=[]
for i in range(1,18):
  categories.append("Symptom_"+str(i))
categories  

['Symptom_1',
 'Symptom_2',
 'Symptom_3',
 'Symptom_4',
 'Symptom_5',
 'Symptom_6',
 'Symptom_7',
 'Symptom_8',
 'Symptom_9',
 'Symptom_10',
 'Symptom_11',
 'Symptom_12',
 'Symptom_13',
 'Symptom_14',
 'Symptom_15',
 'Symptom_16',
 'Symptom_17']

In [21]:
for symptom_index in categories:
  for row_index in dataframe.index:
    if(isinstance(dataframe[symptom_index][row_index],int)!=True and dataframe[symptom_index][row_index]!='foul_smell_of urine' and dataframe[symptom_index][row_index]!='dischromic _patches' and dataframe[symptom_index][row_index]!='spotting_ urination'):
      dataframe[symptom_index][row_index]=symptom_values_list.index(dataframe[symptom_index][row_index])+1

In [22]:
df1

Symptom  weight
0                 itching       1
1               skin_rash       3
2    nodal_skin_eruptions       4
3     continuous_sneezing       4
4               shivering       5
..                    ...     ...
128    inflammatory_nails       2
129               blister       4
130  red_sore_around_nose       2
131     yellow_crust_ooze       3
132             prognosis       5

[133 rows x 2 columns]

In [23]:
dataframe=dataframe.replace('dischromic _patches', 134)
dataframe=dataframe.replace('spotting_ urination',135)
dataframe=dataframe.replace('foul_smell_of urine',136)

In [24]:
symptom_values_list.append('dischromic _patches')
symptom_values_list.append('spotting_ urination')
symptom_values_list.append('foul_smell_of urine')

In [25]:
(dataframe[categories] == 0).all()

Symptom_1     False
Symptom_2     False
Symptom_3     False
Symptom_4     False
Symptom_5     False
Symptom_6     False
Symptom_7     False
Symptom_8     False
Symptom_9     False
Symptom_10    False
Symptom_11    False
Symptom_12    False
Symptom_13    False
Symptom_14    False
Symptom_15    False
Symptom_16    False
Symptom_17    False
dtype: bool

In [26]:
#Dataframe after preprocessing
dataframe

Disease  Symptom_1  Symptom_2  Symptom_3  Symptom_4  Symptom_5  \
0           1          1          2          3        134          0   
1           1          2          3        134          0          0   
2           1          1          3        134          0          0   
3           1          1          2        134          0          0   
4           1          1          2          3          0          0   
...       ...        ...        ...        ...        ...        ...   
4915       37         12         32         35         85         86   
4916       38          2        122        123        124          0   
4917       39         13         90        136         92          0   
4918       40          2          7        125        126        127   
4919       41          2         26        129        130        131   

      Symptom_6  Symptom_7  Symptom_8  Symptom_9  Symptom_10  Symptom_11  \
0             0          0          0          0           0           0   
1             0          0          0          0           0           0   
2             0          0          0          0           0           0   
3             0          0          0          0           0           0   
4             0          0          0          0           0           0   
...         ...        ...        ...        ...         ...         ...   
4915         87          0          0          0           0           0   
4916          0          0          0          0           0           0   
4917          0          0          0          0           0           0   
4918        128          0          0          0           0           0   
4919          0          0          0          0           0           0   

      Symptom_12  Symptom_13  Symptom_14  Symptom_15  Symptom_16  Symptom_17  
0              0           0           0           0           0           0  
1              0           0           0           0           0           0  
2              0           0           0           0           0           0  
3              0           0           0           0           0           0  
4              0           0           0           0           0           0  
...          ...         ...         ...         ...         ...         ...  
4915           0           0           0           0           0           0  
4916           0           0           0           0           0           0  
4917           0           0           0           0           0           0  
4918           0           0           0           0           0           0  
4919           0           0           0           0           0           0  

[4920 rows x 18 columns]

In [27]:
#Taking integer values from the dataframe to create testing and training samples
x=dataframe.loc[:,"Symptom_1":"Symptom_17"].values
y=dataframe.loc[:,"Disease"].values

In [28]:
x

array([[  1,   2,   3, ...,   0,   0,   0],
       [  2,   3, 134, ...,   0,   0,   0],
       [  1,   3, 134, ...,   0,   0,   0],
       ...,
       [ 13,  90, 136, ...,   0,   0,   0],
       [  2,   7, 125, ...,   0,   0,   0],
       [  2,  26, 129, ...,   0,   0,   0]], dtype=int64)

In [29]:
y

array([ 1,  1,  1, ..., 39, 40, 41], dtype=int64)

In [30]:
#Creating training and test samples
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0,shuffle=True)

In [31]:
x_train

array([[  1,  22,  33, ...,   0,   0,   0],
       [  1,  12,  15, ...,   0,   0,   0],
       [ 15,  16,  18, ...,   0,   0,   0],
       ...,
       [  4,   5, 104, ...,   0,   0,   0],
       [ 12,  33,  40, ...,   0,   0,   0],
       [  4,   6,  15, ...,  57,  89,  98]], dtype=int64)

In [32]:
x_test

array([[ 12,  28,  29, ...,   0,   0,   0],
       [  7,  33,  34, ...,   0,   0,   0],
       [ 12,  15,  20, ..., 118,   0,   0],
       ...,
       [  1,  12,  33, ...,   0,   0,   0],
       [  4,   5,   6, ...,   0,   0,   0],
       [  1,   2,  13, ...,   0,   0,   0]], dtype=int64)

In [33]:
y_train

array([21, 15, 32, ...,  2, 25, 27], dtype=int64)

In [34]:
y_test

array([30, 20, 26, 34,  6, 11, 35, 31, 20, 19, 39, 41,  3, 31,  1, 14, 11,
        7, 32, 32,  7, 23,  5,  5, 28, 27, 39, 29, 15,  2,  4,  5, 29, 23,
       17,  8, 10,  5, 38,  5, 37, 24,  6, 15, 30, 39, 23, 30, 29, 31, 33,
       39,  6, 21, 19, 17, 29, 24, 14, 30, 13, 12, 40, 15, 11, 41,  2, 22,
       29, 17, 25, 14, 15, 14, 32, 26,  9, 30,  9, 15, 40, 24, 38,  4, 35,
        8, 15,  8,  8, 28, 23, 18, 16,  1, 27, 21, 31,  1, 16, 36, 19, 41,
       12, 32,  5, 12, 32, 17, 11, 29,  5, 26, 15, 38, 35, 18, 24, 30, 28,
       10,  1, 34, 24, 19, 15, 40, 28,  1,  6, 18, 35,  3, 41, 39, 27, 16,
       38, 39, 16, 14, 20, 12, 10, 10, 11, 19, 18, 17, 21,  5,  9,  3, 37,
       16,  8,  3, 37, 16,  5,  9,  6, 15, 33,  7,  5, 10, 13,  3, 20, 26,
       21, 41, 32, 20, 40, 20,  7, 24,  1, 18, 12, 31, 39, 14,  4, 17, 10,
        1, 25, 19, 13, 10,  6, 33, 38, 16, 20, 39, 21,  3,  7, 38, 36,  1,
       31, 15, 16, 13, 12, 23, 29, 16,  3, 17, 18, 15, 37, 14,  7, 31, 31,
       14, 13, 15,  7,  9

In [35]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [36]:
x_train

array([[-0.7423815 , -0.27406646, -0.28661361, ..., -0.20877226,
        -0.19330258, -0.11457492],
       [-0.7423815 , -0.62696019, -0.78126662, ..., -0.20877226,
        -0.19330258, -0.11457492],
       [ 0.13842528, -0.4858027 , -0.69882445, ..., -0.20877226,
        -0.19330258, -0.11457492],
       ...,
       [-0.55363719, -0.8739858 ,  1.66451772, ..., -0.20877226,
        -0.19330258, -0.11457492],
       [-0.05031903,  0.11411665, -0.09424855, ..., -0.20877226,
        -0.19330258, -0.11457492],
       [-0.55363719, -0.83869643, -0.78126662, ...,  3.18237122,
         4.37799739,  8.7279133 ]])

In [37]:
x_test

array([[-0.03337661, -0.08904318, -0.40760062, ..., -0.23794049,
        -0.22470446, -0.14767144],
       [-0.36180247,  0.08425288, -0.26932612, ..., -0.23794049,
        -0.22470446, -0.14767144],
       [-0.03337661, -0.53961291, -0.65649471, ...,  6.1396555 ,
        -0.22470446, -0.14767144],
       ...,
       [-0.7559135 , -0.64359055, -0.29698102, ..., -0.23794049,
        -0.22470446, -0.14767144],
       [-0.55885798, -0.88620502, -1.0436633 , ..., -0.23794049,
        -0.22470446, -0.14767144],
       [-0.7559135 , -0.99018265, -0.85007901, ..., -0.23794049,
        -0.22470446, -0.14767144]])

In [38]:
#Dimensionality Reduction for reducing the training time of the dataset
from sklearn.decomposition import PCA
pca=PCA(n_components=3)
x_train=pca.fit_transform(x_train)
x_test=pca.fit_transform(x_test)

In [39]:
x_train

array([[ 2.33280141, -1.70566708,  0.60739932],
       [ 0.13399027, -0.49182544, -0.50214537],
       [ 4.64024419, -0.85257195,  1.13817545],
       ...,
       [-1.15888138,  0.38879764,  0.79887654],
       [-0.87814172, -0.63875127, -2.6841382 ],
       [ 5.87335383,  7.26949504, -1.42250286]])

In [47]:
x_test

array([[-0.84804261,  0.2664913 , -1.61342984],
       [ 1.00546192, -1.44027713, -0.1414402 ],
       [ 4.17498589,  3.4251893 ,  0.14485015],
       ...,
       [-0.85675014, -0.0254357 , -0.2220441 ],
       [-1.08557213,  0.38714365, -1.41689042],
       [-1.28407922,  0.48676112, -1.32717703]])

In [40]:
#Result Dictionary carries the accuracy of each trained model
Prediction_List=[]

In [41]:
#Method1=LogisticalRegression

In [42]:
#Method2=NaiveBayes

In [43]:
#Method3=KNNClassification

In [44]:
#Method4=SVM

In [45]:
#Method5=DecisionTree

In [46]:
#Method6=RandomForest